copy/cut select image and text together.
singerdmx/flutter-quill pull request #1307
Opened 2023-07-15 03:53 UTC by TheHeBoy

copy/cut select image and text together.

https://github.com/singerdmx/flutter-quill/assets/49644098/75508d5f-e8ea-42e2-b9cb-087592515502

2023-07-15 03:54 UTC, singerdmx requested changes
Please format code
And update changelog

2023-07-15 04:00 UTC, singerdmx commented
warning • Unused import: '../models/documents/style.dart' • lib/src/widgets/editor.dart:16:8 • unused_import
warning • Unused import: '../models/documents/style.dart' • lib/src/widgets/raw_editor.dart:23:8 • unused_import
   info • The import of '../../models/documents/document.dart' is unnecessary because all of the used elements are also provided by the import of '../../../flutter_quill.dart' • lib/src/widgets/raw_editor/raw_editor_state_selection_delegate_mixin.dart:7:8 • unnecessary_import
   info • The import of '../../models/documents/nodes/leaf.dart' is unnecessary because all of the used elements are also provided by the import of '../../../flutter_quill.dart' • lib/src/widgets/raw_editor/raw_editor_state_selection_delegate_mixin.dart:8:8 • unnecessary_import
   info • The import of '../editor.dart' is unnecessary because all of the used elements are also provided by the import of '../../../flutter_quill.dart' • lib/src/widgets/raw_editor/raw_editor_state_selection_delegate_mixin.dart:[10](https://github.com/singerdmx/flutter-quill/actions/runs/5560278692/jobs/10157148635?pr=1307#step:7:11):8 • unnecessary_import

2023-07-15 04:01 UTC, singerdmx commented
Please don't use` ../../../flutter_quill.dart`

2023-07-15 04:02 UTC, singerdmx commented on lib/src/widgets/raw_editor/raw_editor_state_selection_delegate_mixin.dart
> +import '../../../flutter_quill.dart';
Please don't use `import '../../../flutter_quill.dart';`

2023-07-15 04:08 UTC, singerdmx requested changes

2023-07-15 04:08 UTC, singerdmx commented on lib/src/models/documents/document.dart
> +  List<OffsetValue> collectAllIndividualStyleAndEmbed(int index, int len) {
Can you add comments for this method?

2023-07-15 04:10 UTC, singerdmx requested changes

2023-07-15 04:10 UTC, singerdmx commented on lib/src/widgets/controller.dart
> +  List<OffsetValue> getAllIndividualSelectionStylesAndEmbed() {
Can you add comments for this meth or?

2023-07-15 04:12 UTC, singerdmx requested changes

2023-07-15 04:12 UTC, singerdmx commented on lib/src/widgets/raw_editor/raw_editor_state_selection_delegate_mixin.dart
> +  bool isContainEmbed = false;
This seems hacky

2023-07-15 04:15 UTC, singerdmx commented on lib/src/widgets/raw_editor/raw_editor_state_selection_delegate_mixin.dart
> +    }else if(isContainEmbed){
Can you remove the use of `isContainEmbed`?
For the least you can iterate through pasteStyleAndEmbed and check if there is any `style is Embeddabl`

2023-07-15 05:34 UTC, TheHeBoy commented on lib/src/widgets/raw_editor/raw_editor_state_selection_delegate_mixin.dart
> +    }else if(isContainEmbed){
```
  void _applyPasteStyle(String insertedText, int start) {
    if (insertedText == pastePlainText && pastePlainText != '') {
```
When I only paste images or backspace line head to the previous row, _applyPasteStyle method will be invoked and pastePlainText both are ''. I do not know whether paste the image. And that pasteStyleAndEmbed will not be clear for repetitive paste.

2023-07-15 05:40 UTC, TheHeBoy commented
> Please format code And update changelog

What's mean by "update changelog"? Need me to add text  #[7.2.12]?

2023-07-15 05:41 UTC, singerdmx commented
> > Please format code And update changelog
> 
> What's mean by "update changelog"? Need me to add text #[7.2.12]?

Yes

2023-07-15 05:43 UTC, singerdmx commented on lib/src/widgets/raw_editor/raw_editor_state_selection_delegate_mixin.dart
> +    }else if(isContainEmbed){
both `_adjustInsertedText` and `_applyPasteStyle` are invoked inside `set textEditingValue(TextEditingValue value)`

I am sure you have a better way

2023-07-15 05:45 UTC, singerdmx commented on lib/src/widgets/raw_editor/raw_editor_state_selection_delegate_mixin.dart
> +    }else if(isContainEmbed){
I can schedule a call with to go through the logic

2023-07-15 06:08 UTC, TheHeBoy commented on lib/src/widgets/raw_editor/raw_editor_state_selection_delegate_mixin.dart
> +    }else if(isContainEmbed){
The adjusted code is as follows, is ok?
```dart
  set textEditingValue(TextEditingValue value) {
    final cursorPosition = value.selection.extentOffset;
    final oldText = widget.controller.document.toPlainText();
    final newText = value.text;
    final diff = getDiff(oldText, newText, cursorPosition);
    if (diff.deleted == '' && diff.inserted == '') {
      // Only changing selection range
      widget.controller.updateSelection(value.selection, ChangeSource.LOCAL);
      return;
    }

    var isContainEmbed = false;
    var insertedText = diff.inserted;
    if (insertedText.codeUnits.contains(Embed.kObjectReplacementInt)) {
      isContainEmbed = true;
      insertedText = _adjustInsertedText(diff.inserted);
    }

    widget.controller.replaceText(
        diff.start, diff.deleted.length, insertedText, value.selection);

    _applyPasteStyle(insertedText, diff.start, isContainEmbed);
  }

  void _applyPasteStyle(String insertedText, int start, bool isContainEmbed) {
    if (insertedText == pastePlainText && pastePlainText != '') {
      final pos = start;
      for (var i = 0; i < pasteStyleAndEmbed.length; i++) {
        final offset = pasteStyleAndEmbed[i].offset;
        final styleAndEmbed = pasteStyleAndEmbed[i].value;

        if (styleAndEmbed is Embeddable) {
          widget.controller.replaceText(pos + offset, 0, styleAndEmbed, null);
        } else {
          widget.controller.formatTextStyle(
              pos + offset,
              i == pasteStyleAndEmbed.length - 1
                  ? pastePlainText.length - offset
                  : pasteStyleAndEmbed[i + 1].offset,
              styleAndEmbed);
        }
      }
    } else if (isContainEmbed) {
      final pos = start;
      for (var i = 0; i < pasteStyleAndEmbed.length; i++) {
        final offset = pasteStyleAndEmbed[i].offset;
        final style = pasteStyleAndEmbed[i].value;
        if (style is Embeddable) {
          widget.controller.replaceText(pos + offset, 0, style, null);
        }
      }
    }
  }

  String _adjustInsertedText(String text) {
    final sb = StringBuffer();
    for (var i = 0; i < text.length; i++) {
      if (text.codeUnitAt(i) == Embed.kObjectReplacementInt) {
        continue;
      }
      sb.write(text[i]);
    }
    return sb.toString();
  }
```

2023-07-15 06:11 UTC, singerdmx commented on lib/src/widgets/raw_editor/raw_editor_state_selection_delegate_mixin.dart
> +    }else if(isContainEmbed){
Thanks! much better.
But `_applyPasteStyle` seems to have duplicated code which can be improved.
Also we may want to rename it to `_applyPasteStyleAndEmbed` ?

2023-07-15 06:13 UTC, singerdmx commented on lib/src/widgets/raw_editor/raw_editor_state_selection_delegate_mixin.dart
> +    }else if(isContainEmbed){
```
var containsEmbed = insertedText.codeUnits.contains(Embed.kObjectReplacementInt);
var insertedText = diff.inserted;
if (containsEmbed) {
      insertedText = _adjustInsertedText(diff.inserted);
}
```

2023-07-15 06:22 UTC, TheHeBoy commented on lib/src/widgets/raw_editor/raw_editor_state_selection_delegate_mixin.dart
> +    }else if(isContainEmbed){
Yes, you are right.

2023-07-15 06:22 UTC, singerdmx commented on lib/src/widgets/raw_editor/raw_editor_state_selection_delegate_mixin.dart
> +    }else if(isContainEmbed){
```
void _applyPasteStyleAndEmbed(String insertedText, int start, bool containsEmbed) {
  if (insertedText == pastePlainText && pastePlainText != '' || containsEmbed) {
    final pos = start;
    for (var i = 0; i < pasteStyleAndEmbed.length; i++) {
      final offset = pasteStyleAndEmbed[i].offset;
      final styleAndEmbed = pasteStyleAndEmbed[i].value;

      if (styleAndEmbed is Embeddable) {
        widget.controller.replaceText(pos + offset, 0, styleAndEmbed, null);
      } else {
        widget.controller.formatTextStyle(
          pos + offset,
          i == pasteStyleAndEmbed.length - 1
              ? pastePlainText.length - offset
              : pasteStyleAndEmbed[i + 1].offset,
          styleAndEmbed);
      }
    }
  }
}

```

2023-07-15 06:45 UTC, singerdmx commented on lib/src/widgets/raw_editor/raw_editor_state_selection_delegate_mixin.dart
> +    }else if(isContainEmbed){
```
var containsEmbed = insertedText.codeUnits.contains(Embed.kObjectReplacementInt);
var insertedText = containsEmbed ? _adjustInsertedText(diff.inserted) : diff.inserted;
```

2023-07-15 06:46 UTC, TheHeBoy commented on lib/src/widgets/raw_editor/raw_editor_state_selection_delegate_mixin.dart
> +    }else if(isContainEmbed){
Thanks! You make code more Concise

2023-07-15 07:00 UTC, singerdmx commented on lib/src/models/documents/nodes/line.dart
> +  List<OffsetValue> collectAllIndividualStylesAndEmbed(int offset, int len,
```
List<OffsetValue> collectAllIndividualStylesAndEmbed(int offset, int len,
    {int beg = 0}) {
  final local = math.min(length - offset, len);
  final result = <OffsetValue>[];

  final data = queryChild(offset, true);
  var node = data.node as Leaf?;
  var pos = 0;

  while (node != null && pos < local) {
    if (node is Text || node.value is Embeddable) {
      pos = node.length - data.offset;
      result.add(OffsetValue(beg, node is Text ? node.style : node.value as Embeddable));
      pos += node.length;
    }
    if (!node.isLast) {
      node = node.next as Leaf;
    } else {
      break;
    }
  }

  final remaining = len - local;
  if (remaining > 0 && nextLine != null) {
    final rest = nextLine!.collectAllIndividualStylesAndEmbed(0, remaining, beg: local);
    result.addAll(rest);
  }

  return result;
}

```

2023-07-15 07:02 UTC, singerdmx commented on lib/src/models/documents/nodes/line.dart
> +  List<OffsetValue> collectAllIndividualStylesAndEmbed(int offset, int len,
Please remove `collectAllIndividualStyles` method

2023-07-15 07:04 UTC, singerdmx commented on lib/src/models/documents/document.dart
> +  List<OffsetValue> collectAllIndividualStyleAndEmbed(int index, int len) {
Please remove `collectAllIndividualStyles`

2023-07-15 07:05 UTC, singerdmx commented
Need to replace the test:


  ```
  test('getAllIndividualSelectionStyles', () {
      controller.formatText(0, 2, Attribute.bold);
      final result = controller.getAllIndividualSelectionStyles();
      expect(result.length, 1);
      expect(result[0].offset, 0);
      expect(result[0].value, Style().put(Attribute.bold));
    });
```

2023-07-15 09:27 UTC, TheHeBoy commented on lib/src/models/documents/nodes/line.dart
> +  List<OffsetValue> collectAllIndividualStylesAndEmbed(int offset, int len,
The above code has a worry mistake. Can't together paste text and image.And I haven't more much idea for this,The adjusted code is as follows:
```
  List<OffsetValue> collectAllIndividualStylesAndEmbed(int offset, int len,
      {int beg = 0}) {
    final local = math.min(length - offset, len);
    final result = <OffsetValue>[];

    final data = queryChild(offset, true);
    var node = data.node as Leaf?;
    if (node != null) {
      var pos = 0;
      if (node is Text || node.value is Embeddable) {
        pos = node.length - data.offset;
        result.add(OffsetValue(
            beg, node is Text ? node.style : node.value as Embeddable));
      }
      while (!node!.isLast && pos < local) {
        node = node.next as Leaf;
        if (node is Text || node.value is Embeddable) {
          result.add(OffsetValue(
              pos + beg, node is Text ? node.style : node.value as Embeddable));
          pos += node.length;
        }
      }
    }

    final remaining = len - local;
    if (remaining > 0 && nextLine != null) {
      final rest = nextLine!
          .collectAllIndividualStylesAndEmbed(0, remaining, beg: local);
      result.addAll(rest);
    }

    return result;
  }
```

2023-07-16 01:10 UTC, singerdmx commented
Can you update this PR please?

2023-07-16 01:48 UTC, merged