Fix my issues and changes
singerdmx/flutter-quill pull request #1417
Opened 2023-10-02 23:06 UTC by ahmedhnewa

I have used gal instead of image_gallery_saver

I didn't change the packages and plugin versions

Please change it to fit your needs

[Code documentation and a new event for confirm removal of the image](https://github.com/singerdmx/flutter-quill/pull/1414)
[Improvements and one new event](https://github.com/singerdmx/flutter-quill/pull/1413)

2023-10-02 23:08 UTC, singerdmx commented
You need to rebase

2023-10-02 23:13 UTC, singerdmx commented
@Jon-Salmon please have a look

2023-10-04 07:26 UTC, Jon-Salmon requested changes
Thanks for the updates! Just one small nit, but happy for this to be merged after changing that one small bit.

2023-10-04 07:26 UTC, Jon-Salmon commented on flutter_quill_extensions/lib/flutter_quill_extensions.dart
> -              (imageFile) async {
I was mainly referring only to `shouldRemoveImageFromEdtior` about it being optional. There is nothing wrong with this being optional too, but we should still provide this sensible default here.

2023-10-04 07:47 UTC, ahmedhnewa commented
> Thanks for the updates! Just one small nit, but happy for this to be merged after changing that one small bit.

Thank you for your concern about this great plugin, I think we need to change the documentation of some of the changed code

I mentioned that the image by default will be removed from the local storage if it is removed from the editor from Quill Delta

But now it will not do anything by default

Instead, in the documentation, we should only show the developer who uses this package how to do it himself since it's not by default

I also suggest changing the names of the parameters that I have added

I mean, it could be shorter and more descriptive, but I was lazy, to be honest, since I already mentioned that I didn't have enough time to make more changes

If you want me to make these changes by myself, please tell me to do it

Or if you can handle it and you think you will do it better, then be my guest.

Thank you for your time and efforts again to the community.

2023-10-04 07:51 UTC, ahmedhnewa commented on flutter_quill_extensions/lib/flutter_quill_extensions.dart
> -              (imageFile) async {
> I was mainly referring only to `shouldRemoveImageFromEdtior` about it being optional. There is nothing wrong with this being optional too, but we should still provide this sensible default here.

I agree with you, but then we shouldn't change the documentation code

As I suggest in my previous comment

And I was mainly refering to afterRemoveImageFromEditor

2023-10-04 15:26 UTC, singerdmx commented
LGTM

2023-10-04 18:33 UTC, Jon-Salmon commented
Thanks for the contributions. I'll make some documentation changes and release a new version shortly

2023-10-04 18:33 UTC, merged