New features and improvements
singerdmx/flutter-quill pull request #1419
Opened 2023-10-05 08:31 UTC by ahmedhnewa

Features:

1. The desktop context menu that shows when you click on the image was quite buggy on macOS, so I added an option to the developer to force the use of the mobile context menu but the resizing feature will not be available only on desktop, I excluded it as option
2. Add `QuillImageUtilities` class which has helpful functions for developers, you could remove this if you want to

Improvements:

- The way is to check if the video URL is from YouTube or not handled in a better way
- Better documentations
- Important: The default action when removing the image from the editor is to delete the image if it exists, however on desktop we don't want to touch user files since the way to handle files on desktop is different from mobile (iOS, Android) so I handle this as well, otherwise, users will get a crash when we remove the image øn macOS, on other desktop platforms the app will delete the user image which something we should never do as developers, the trust is important as humans not just between developers and users
- the isImageBase64() has been improved

And I don't know where there is a conflict between all the branches and some changes I already made before
Sorry for that conflict, I haven't slept in a while so I'm not really focused, I could make more mistakes

And speaking of mistakes, the library should be tested on Windows and Linux as well

I have noticed some other bugs in the editor on macOS that are not related to the changes I made

Also on the web, there is a small issue I will leave it for someone else for now, but if no one migrates the code then I will have to do it myself

[Web issue](https://github.com/singerdmx/flutter-quill/issues/1418)

Give me a moments and I will rebase soon

2023-10-05 15:03 UTC, singerdmx approved these changes
@Jon-Salmon please have a look

2023-10-09 20:36 UTC, singerdmx commented
@Jon-Salmon ping

2023-10-10 08:07 UTC, Jon-Salmon requested changes
In general I'm happy with what you're trying to add, but a lot of this code is quite mangled up from what looks like being based off an old branch. I've tried to highlight where these issues are, but you are probably best rebasing off the current main.

Also, please update the changelog file

2023-10-11 12:03 UTC, freshtechtips commented on flutter_quill_extensions/lib/flutter_quill_extensions.dart
> +  ///       message: 'Are you sure you want' ' to delete this
It just gives a better look in the IDE for smaller screens in development, you can change this and I didn't plan on change this

2023-10-11 12:06 UTC, freshtechtips commented on flutter_quill_extensions/pubspec.yaml
> -version: 0.5.0
I didn't fetch the latest changes and the version I have was quite outdated

2023-10-11 12:06 UTC, freshtechtips commented on flutter_quill_extensions/pubspec.yaml
> -  flutter_quill: ^7.4.7
You are right

2023-10-11 12:13 UTC, freshtechtips commented on flutter_quill_extensions/lib/embeds/builders.dart
> +  final ImageEmbedBuilderWillRemoveCallback? onImageRemovedCallback;
Can you explain in more detail?

2023-10-11 12:15 UTC, freshtechtips commented on flutter_quill_extensions/lib/embeds/builders.dart
> +  final ImageEmbedBuilderWillRemoveCallback? onImageRemovedCallback;
I will fix it soon

2023-10-11 12:21 UTC, freshtechtips commented on flutter_quill_extensions/lib/embeds/builders.dart
> -                    // Call the remove check callback if set
Can you explain the issue in more detail so I can fix it??

2023-10-11 12:21 UTC, freshtechtips commented on flutter_quill_extensions/lib/embeds/embed_types.dart
> -typedef ImageEmbedBuilderWillRemoveCallback = Future<bool> Function(
It will be fixed in the next commit

2023-10-11 12:22 UTC, freshtechtips commented on flutter_quill_extensions/lib/flutter_quill_extensions.dart
> -    ImageEmbedBuilderOnRemovedCallback? onImageRemovedCallback,
+ It will be fixed in the next commit

2023-10-11 13:44 UTC, freshtechtips commented on flutter_quill_extensions/lib/utils/quill_utils.dart
> +import 'dart:io' show Directory, File, Platform;
The QuillImageUtilities doesn't work on the web, for now, I have updated the comments

If the developer tries to call it on the web he will get UnsupportedError

2023-10-11 13:46 UTC, freshtechtips commented on flutter_quill_extensions/lib/utils/quill_utils.dart
> +    final imagesPaths = getImagesPathsFromDocument(
Yes we need since the dart:io it not supported on web and we need different solution but I will leave it for now

2023-10-11 13:47 UTC, freshtechtips commented on flutter_quill_extensions/lib/flutter_quill_extensions.dart
> +  ///       message: 'Are you sure you want' ' to delete this
Please change it to fit your needs and what you think it's best for the project and other developers that are working on this project

2023-10-11 13:59 UTC, freshtechtips commented
I have fixed almost all the issues, as I mentioned in the previous pull request my sleep is not regular
and this is why I made too many mistakes in the new pull request

Thank you for your time and efforts.

2023-10-12 07:23 UTC, singerdmx commented on CHANGELOG.md
>  # [7.4.9]
Add a line break

2023-10-12 07:24 UTC, singerdmx approved these changes

2023-10-12 10:06 UTC, freshtechtips commented on CHANGELOG.md
>  # [7.4.9]
> Add a line break

Hi, do you want me to change this like requested and push a new commit??

2023-10-12 14:55 UTC, singerdmx commented on CHANGELOG.md
>  # [7.4.9]
Yes if you can
Just add a blank line

2023-10-13 04:21 UTC, cahyofendhi commented
> I have fixed almost all the issues, as I mentioned in the previous pull request my sleep is not regular and this is why I made too many mistakes in the new pull request
> 
> Thank you for your time and efforts.

thanks

2023-10-14 16:09 UTC, singerdmx commented
@Jon-Salmon ping

2023-10-16 19:29 UTC, Jon-Salmon requested changes

2023-10-16 19:29 UTC, Jon-Salmon commented on flutter_quill_extensions/pubspec.yaml
> +  math_keyboard: ">=0.2.1"
Please don't adjust the dependency ranges unless there is a reason to do so (i.e. something is not supported). Here you have removed the upper bound on `math_keyboard` for example which should not be done

2023-10-16 19:30 UTC, Jon-Salmon commented
Looks pretty good! One final change from my perspective and then LGTM

2023-10-17 03:56 UTC, singerdmx commented
@freshtechtips please make the final change and let's merge it

2023-10-17 10:55 UTC, freshtechtips commented on flutter_quill_extensions/pubspec.yaml
> +  math_keyboard: ">=0.2.1"
Hi, can you explain in detail what I should do?  just change the version of youtube_player_flutter to `youtube_player_flutter: ^8.1.1`?? But why ?? most developers will not override the version and it's a good idea to use the latest version to get the latest improvemenets

2023-10-17 10:58 UTC, freshtechtips commented on flutter_quill_extensions/pubspec.yaml
> +  math_keyboard: ">=0.2.1"
Please take a look at [Device info plus change log](https://pub.dev/packages/device_info_plus/changelog)
it's an important change, in my opinion, I just upgraded to 10 but after a few days it gets removed and replaced with a smaller version

2023-10-17 15:19 UTC, singerdmx commented
@freshtechtips can you resolve the conflict and I will merge it

2023-10-17 15:22 UTC, singerdmx commented
The conflict is from change log and version

2023-10-17 16:21 UTC, freshtechtips commented
I fixed the conflicts and pushed the changes however it still shows me the message "This branch has conflicts that must be resolved" Do I need to do this in GitHub?? and then fetch the changes to merge them with my local one?? I want my local repository to be up to date because I plan on sending more pull requests for further improvements, that is if you want to or don't mind

2023-10-17 16:23 UTC, freshtechtips commented
I did it from remote one on github since I will rebase anyway

2023-10-17 16:41 UTC, merged

2023-10-17 16:42 UTC, singerdmx commented
@Jon-Salmon you can make additional changes per your preference