Add padding control in for toolbar buttons
singerdmx/flutter-quill pull request #1592
Opened 2023-12-12 04:20 UTC by mark8044

So many controls for the appearance of toolbar buttons has been lost.  Adding them back in one by one.  In this case padding control is added via the QuillIconTheme class

2023-12-12 05:38 UTC, singerdmx requested changes

2023-12-12 05:38 UTC, singerdmx commented on lib/src/widgets/toolbar/buttons/quill_icon_button.dart
> +      padding: (padding != null) ? padding : null,
Why not just padding?

2023-12-12 05:57 UTC, mark8044 reviewed
ok

2023-12-12 06:54 UTC, singerdmx approved these changes

2023-12-12 06:55 UTC, singerdmx commented
@freshtechtips please take a look

2023-12-12 06:57 UTC, singerdmx commented
info • The import of 'package:flutter/widgets.dart' is unnecessary because all of the used elements are also provided by the import of 'package:flutter/material.dart' • lib/src/models/themes/quill_icon_theme.dart:1:8 • unnecessary_import
   info • Sort directive sections alphabetically • lib/src/models/themes/quill_icon_theme.dart:2:1 • directives_ordering
   info • The import of 'package:meta/meta.dart' is unnecessary because all of the used elements are also provided by the import of 'package:flutter/material.dart' • lib/src/models/themes/quill_icon_theme.dart:3:8 • unnecessary_import
   info • Use 'const' with the constructor to improve performance • lib/src/widgets/toolbar/buttons/quill_icon_button.dart:27:22 • prefer_const_constructors
   info • Use 'const' with the constructor to improve performance • lib/src/widgets/toolbar/buttons/quill_icon_button.dart:32:20 • prefer_const_constructors

Are you able to address the CI failure?

2023-12-12 09:28 UTC, freshtechtips commented
I'm against this change 

Flutter keeps changing those, and we can't keep track of all of them 

Even the customization options in the quill toolbar

Instead, I think we should encourage them to create his own toolbar using our widgets and buttons and customize them using childBuilder

It will be more efficient and similar to quill js

If you guys insisted, then after we accept this change

We need to do more

What do you think, @singerdmx ?

2023-12-12 14:50 UTC, mark8044 commented
You are against this change?   
- How else does one control padding of an IconButton?  
- When has flutter ever changed the way EdgeInsets work or the padding parameter of an IconButon?  ANSWER: Never

Since you bring up some important topics of customization (you brought this up and not me):
1. These icons USED to be customizable, somehow you stripped them of all that.  You regressed the project. It seems like you made significant breaking changes to everything in the toolbar without considering other people.  This is an OPEN SOURCE project.  This is not YOUR project. 

2. Why would you want to encourage people to use your own widget to make a custom toolbar with childBuilder?  Is it because you think this is YOUR PROJECT and you want to force people in to your way with breaking changes?  That's what forks are for.  Fork and do whatever crazy thing you want on your own end.

3. On the topic of using your widgets and efficency (you brought this up), here's why its a terrible idea to have people use your custom widgets:   Look at just this file we are adding padding to.  In order to highlight a simple button you are constantly swapping out the ENTIRE IconButton widget.  Why?  How does that make any sense?  Even the callback is carried with only one of the widgets (not filled).   Logically we should use the method flutter recommends and every app programmer uses: STATE changes on the SAME widget. Swapping the entire widget introduces so much bloat and inefficiency.  Just to add in a simple padding change I had to do it in two different places.  My app is eating more memory every time someone clicks a toolbar icon.  Have you run a memory profiler on the changes you've made.  You would be shocked.   Look at have janky the project has become.   Its a mess.   If you are at all serious about efficiency, then we need to roll back all these changes back into June-July

4. You have created now 2-3 CONFLICTING paths (theme, direct icon options and option class) for someone to try to change icon color but closed off the path for someone to control the background, size, shape, spacing or otherwise using any of those conflicting paths.  Seems illogical, but Im assuming you just didn't notice along with all the other regressions.


Im surprised anyone would be against a simple NON BREAKING change to padding.   It just says that you think this project is yours and you get to make the changes.  You make it clear you made these changes just for your own project: https://github.com/singerdmx/flutter-quill/discussions/1441.   That would be OK if you didn't need to break everyone else's in the process or at least waste so many peoples time trying to adapt their code to these changes.  Remind me again why we moved everything into QuillProvider then back out again?


I have a few more **NON BREAKING** PRs to add which would add back in basic control of the tool bar icons.  Mind you this is to add back in what was already there, so yes wasting time to just get things up to basic function that was already there.  

Sorry for the long winded message.  I just wanted to be clear and see if this is your repo now and thus its a waste of time to contribute here any longer, or if there is any use to try to fix what is totally broken.  Like the advice I gave to you, I am happy to take it for myself and I can fork and move on as well.  Im sure many others are right now sitting on older versions until dependencies break and then would walk away to an alternative.  This is a hot mess.

Up to @singerdmx which direction he wants to go.  The original codebase was slim, readable, manageable and FAST.  This right now is really bad.

2023-12-12 14:54 UTC, freshtechtips commented
Calm down I didn't mean it this way, I'm just sharing an idea with the owner and he do what he wants
he would like to make it more like quill js but for flutter

2023-12-12 14:55 UTC, freshtechtips commented
This is not my project, by I'm aginst this, I'm just saying we made a new way of things that confirms to quill js

I didn't want to publish version 9.0.0 but I was forced to

2023-12-12 15:00 UTC, freshtechtips commented
Run `dart fix --apply` or fix the analysis warnings manually, and we will merge it, even though it will be aginst quill js

2023-12-12 15:01 UTC, mark8044 commented
> This is not my project, by I'm against this, I'm just saying we made a new way of doing things that confirms to quill js
> 
> I didn't want to publish version 9.0.0 but I was forced to
> 
> People really don't like the idea of `QuillProvider` and I didn't have time to create separate branch and commit for dropping it alone
> 
> if you have the time, then I would like @singerdmx to make you a maintainer and I will do whatever you want just so you feel it's your project and your thing, if that's what you want or probably you don't
> 
> I will even help you with your affected projects just keep calm and study, otherwise we will not get any result,

I don't need to be a maintainer, Im happy to contribute to this project.  I have already made contributions here in the past, yes I am not the best and @singerdmx had to teach me alot, but I did it in way to not break other people projects.  That's the point, open source.

2023-12-12 15:06 UTC, freshtechtips commented
Regarding the code base I hate to break it to you but it was already messy, for example the whole code of raw editor is all in one file (more than 5000 lines)

Yes I didn't split it in perfect way but we are working, we need your patience and help

2023-12-12 15:08 UTC, mark8044 commented
> Run `dart fix --apply` or fix the analysis warnings manually and I will maintain it later just when I have time, because at the moments I really don't and that's not up to me or the maintainers of the repo, and we will merge it, even though it will be against quill js

What do you mean against quill js?  
Why do you care about Quill JS?  
What does dart or flutter structure have to do with JS and why are you using that as a model for anything?  There is not even a connection between the two.  And yes I am VERY familiar with JS (stronger in JS then dart) and even Titanium apps (JS based cross platform apps).   There are no similarities between JS and Widget based structure of flutter, so I would love to hear what that even means 'against quill js'

2023-12-12 15:09 UTC, freshtechtips commented
> > Run `dart fix --apply` or fix the analysis warnings manually and I will maintain it later just when I have time, because at the moments I really don't and that's not up to me or the maintainers of the repo, and we will merge it, even though it will be against quill js
> 
> What do you mean against quill js? Why do you care about Quill JS? What does dart or flutter structure have to do with JS and why are you using that as a model for anything? There is not even a connection between the two. And yes I am VERY familiar with JS (stronger in JS then dart) and even Titanium apps (JS based cross platform apps). There are no similarities between JS and Widget based structure of flutter, so I would love to hear what that even means 'against quill js'

Great to hear you are strong in js, I meant the quill js doesn't provide you a prebuilt toolbar with many options, it just provide you the things you need and you set it up, along with the buttons

2023-12-12 15:10 UTC, mark8044 commented
> Regarding the code base I hate to break it to you but it was already messy, for example the whole code of raw editor is all in one file (more than 5000 lines)
> 
> it has a lot of bugs too, the example was completely wrong, the translations was hard to maintain and much more but there is no need talk about it, it's a waste of time just like you said
> 
> Yes I didn't split it in perfect way but we are working, we need your patience and help

What does the code base for raw editor have to do with these toolbar icons?  You are changing the subject for no reason.

Help is fine and help is good.  But breaking things and then ask for help fix what I broke is not the correct way. You will find little to no help.   Then when someone actually does fix it, we have now a long trail of messages over literally adding padding to an IconButton.  LOL

Let that sink in. We are talking about merging a change for EdgeInsets.   LOL

2023-12-12 15:12 UTC, freshtechtips commented
> > Regarding the code base I hate to break it to you but it was already messy, for example the whole code of raw editor is all in one file (more than 5000 lines)
> > it has a lot of bugs too, the example was completely wrong, the translations was hard to maintain and much more but there is no need talk about it, it's a waste of time just like you said
> > Yes I didn't split it in perfect way but we are working, we need your patience and help
> 
> What does the code base for raw editor have to do with these toolbar icons? You are changing the subject for no reason.
> 
> Help is fine and help is good. But breaking things and then ask for help fix what I broke is not the correct way. You will find little to no help. Then when someone actually does fix it, we have now a long trail of messages over literally adding padding to an IconButton. LOL
> 
> Let that sink in. We are talking about merging a change for EdgeInsets. LOL

I'm not asking you for helping fixing my breaking changes, that's on me, I'm asking @singerdmx  a few questions and I will fix it just wait, besides we can revert at anytime so keep calm, not much changed after I joined

2023-12-12 15:12 UTC, freshtechtips commented
Fix the CI failure and we are merging this

2023-12-12 15:24 UTC, freshtechtips commented
Format the code using `dart format .`

2023-12-12 20:16 UTC, freshtechtips commented
Let me know when you are ready to merge

2023-12-12 20:17 UTC, merged

2023-12-13 01:41 UTC, mark8044 commented
Thanks for merging