Toolbar button styling to reflect cursor position when running on desktops with keyboard to move caret.
singerdmx/flutter-quill pull request #1801
Opened 2024-04-02 15:49 UTC by AtlasAutocode

## Description

Proposed changes make the toolbar buttons selection state reflect the styling as the cursor is moved. Using desktop (Windows) keyboard cursor keys to move the caret position (without selecting text).

- Fix inline style tracking: When cursor is moved into a region of bold, the bold style is correctly recognized and reflected in the toolbar status. Problem: When the cursor keys move the caret out of the bold region, the bold style is not cleared and cannot be removed.

- Fix: toggle_style_button failed to call default afterButtonPressed in base button settings. Constructor called options.afterButtonPressed rather than the class function afterButtonPressed that defaults to a call to QuillToolbarBaseButtonOptions.

- Fix: quill_icon_button build when isSelected did not call afterButtonPressed (expected same action as when not selected).

- Fix: QuillController _updateSelection removed param=source because not used; added new param insertNewline to recognize when a newline entered and maintain the correct inline style by correctly setting toggledStyle; updated replaceText to call _updateSelection for newline.

- Fix: document.dart collectStyle:  Click at the start of a line (of bold text), user would expect the style to be the visible style of the line including inline styles. Also requires updating insert.dart PreserveInlineStylesRule to recognize if inserting text at start of line and use attributes from the first char on line

- Fix: color_button : Add afterPressed param to QuillToolbarIconButton

## Related Issues

- *Fix #1786*  QuillToolbarBaseButtonOptions now called

- *Fix #1775*  Toolbar bold button now tracks cursor position

## Improvements

## Features

## Additional notes

## Suggestions
QuillController (public function) updateSelection also does not use the ChangeSource parameter.
ChangeSource enum does not appear to be used anywhere - is this deprecated or am I missing something?

## Checklist

- [X] I read the [Contributor Guide](../CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
- [X] I titled the PR using [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0).
- [X] I did not modify the `CHANGELOG.md` nor the plugin version in `pubspec.yaml` files.
- [X] All existing and new tests are passing.
- [X] I have run the commands in `./scripts/before_push.sh` and it all passed successfully

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate that with a `!` in the title as explained in [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0)).
- [X] No, this is *not* a breaking change.

2024-04-03 01:00 UTC, singerdmx commented
```
Run dart format --set-exit-if-changed .
Formatted lib/src/widgets/quill/quill_controller.dart
Formatted 260 files (1 changed) in 1.33 seconds.
Error: Process completed with exit code 1.
```

2024-04-03 01:02 UTC, singerdmx commented on example/lib/screens/quill/my_quill_toolbar.dart
> -            // buttonOptions: QuillSimpleToolbarButtonOptions(
is this change needed?

2024-04-03 01:03 UTC, singerdmx commented
@ellet0 I am unsure about this PR. Could you please take a look? Thanks!

2024-04-03 13:04 UTC, ellet0 commented
> @ellet0 I am unsure about this PR. Could you please take a look? Thanks!

I'm not sure too about the changes in the insert rule and the document file

The code is getting more and more messy
Only the original authors can understand it

And with all the changes that have been made, I doubt they can understand it now

I can understand the other changes

2024-04-03 13:07 UTC, ellet0 commented
> @ellet0 I am unsure about this PR. Could you please take a look? Thanks!

I'm not sure too about the changes in the insert rule and the document file

The code is getting more and more messy
Only the original authors can understand it

I haven't made any changes to the base of the library (in the document, raw editor widget, the rules, etc...)

I can understand the other changes

2024-04-03 13:11 UTC, ellet0 commented
Please revert all the unnecessary comments that have been made like the ones in the example folder

2024-04-03 17:43 UTC, ellet0 requested changes
Please revert all the unnecessary comments that have been made like the ones in the example folder

2024-04-05 18:32 UTC, AtlasAutocode commented
Changes made and submitted.
This is my first contribution - do I need to do something??

2024-04-06 23:22 UTC, singerdmx commented
@ellet0 can you check this PR again?

2024-04-06 23:24 UTC, singerdmx approved these changes

2024-04-06 23:24 UTC, singerdmx commented
```
Run dart format --set-exit-if-changed .
Formatted lib/src/widgets/quill/quill_controller.dart
Formatted 261 files (1 changed) in 1.2[8](https://github.com/singerdmx/flutter-quill/actions/runs/8544426268/job/23524750239?pr=1801#step:13:9) seconds.
Error: Process completed with exit code 1.
```

2024-04-06 23:25 UTC, singerdmx requested changes
Please fix formatting issue

2024-04-06 23:25 UTC, ellet0 commented
> @ellet0 can you check this PR again?

I'm not familiar with most of the code, and I don't understand why it's what it's and why this change could solve the issues mentioned.

2024-04-08 03:25 UTC, singerdmx commented
> > @ellet0 can you check this PR again?
> 
> I'm not familiar with most of the code, and I don't understand why it's what it's and why this change could solve the issues mentioned.

We just need to test if it fixes the issue the PR mentioned.
If there is issue we can always rollback.

2024-04-13 21:34 UTC, merged