Add support for html underline and videos
singerdmx/flutter-quill pull request #1955
Opened 2024-06-28 19:00 UTC by CatHood0

## Description

If you try to use `DeltaX.fromHtml` with a tag `<u>` to use it as a underline style, then will be removed and just pass content as plain. Videos has the same result of the before one, if you try to use an `<iframe>` will be paste as a plain text or removed (idk really this last one case).

## Related Issues

*Fix #1917* 
*Fix #1945*

## Improvements

- Was added support for local underline syntax to detect and apply on resulting delta.
- Was added support for iframes with video url's (by now just can verify youtube videos)

## Checklist

- [x] I read the [Contributor Guide](../CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
- [x] I titled the PR using [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0).
- [x] I did not modify the `CHANGELOG.md` nor the package version in `pubspec.yaml` files.
- [x] All existing and new tests are passing.
- [x] I have run the commands in `./scripts/before_push.sh` and it all passed successfully

## Breaking Change

Does your PR require developers to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate that with a `!` in the title as explained in [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0)).
- [x] No, this is *not* a breaking change.

2024-06-28 19:18 UTC, ellet0 commented
Thank you for your contributions, I will review and test the changes soon.

2024-06-28 20:18 UTC, ellet0 requested changes
Thank you for adding tests and your contributions once again, I haven't tested this change yet.

Just a few things to consider before releasing this change.

2024-06-28 20:18 UTC, ellet0 commented on lib/src/utils/html2md_utils.dart
> +// ignore_for_file: implementation_imports
Cam, can we avoid creating this file?

It's out of scope for `flutter_quill`, and the reason we have Markdown and HTML converting in `flutter_quill`

It's only to support rich text pasting support,  the reason the convert from HTML and Markdown functions is in `flutter_quill` instead of the converters as the convert to require additional dependencies that I prefer to not using them to avoid add too many dependencies to the developers project.

Once the convert logic is fully rewritten from scratch, we can solve this by adding the converter packages that have minimal dependencies, in short, I prefer to avoid adding logic related to HTML or Delta too much in `flutter_quill`

We only did this for the rich pasting feature. Usually, the user doesn't copy and paste videos, so the current solution works well for this use case. Adding more code to cover more use cases also means more maintenance over time, which is why I prefer to make this optional in the converters or move them somewhere else.

The current project structure could use a lot of refactoring and improvements, which is another reason I prefer to add anything extra.

2024-06-28 20:26 UTC, CatHood0 commented on lib/src/utils/html2md_utils.dart
> +// ignore_for_file: implementation_imports
So, are you suggesting that I delete it completely and move the logic to Deltax again to avoid continuing to create unnecessary files?

2024-06-28 20:29 UTC, CatHood0 commented on lib/src/models/documents/delta_x.dart
> +    Html2MdConfigs? configs,
Then, should i just put in what is necessary to solve the problems with italics, underlines and iframes instead of creating a whole class for its settings?

2024-06-28 20:43 UTC, ellet0 commented on lib/src/utils/html2md_utils.dart
> +// ignore_for_file: implementation_imports
> So, are you suggesting that I delete it completely and move the logic to Deltax again to avoid continuing to create unnecessary files, or just remove video implementation and left just underline fix?


I prefer to avoid creating new files or maybe create a new directory for this.

Yet you can keep both, it's might be a good idea to keep this logic in a new file as you did it to avoid exporting anything as the `DeltaX` class file is exported.

2024-06-28 20:47 UTC, ellet0 commented on lib/src/models/documents/delta_x.dart
> +    Html2MdConfigs? configs,
That's what I suggest. It's not necessary, though.

2024-06-28 22:07 UTC, singerdmx commented on lib/src/utils/html2md_utils.dart
> +// ignore_for_file: implementation_imports
@ellet0 Let's not block feature/fix. We can always refactor/reorganize code around later.

2024-06-28 22:08 UTC, singerdmx commented
@CatHood0 Please resolve the conflict. Please do not worry too much about where is the best place to put the code. I believe @ellet0 can always move around code to make sense OOD wise.

2024-06-28 22:12 UTC, CatHood0 commented on lib/src/utils/html2md_utils.dart
> +// ignore_for_file: implementation_imports
Sorry, i'm force a commit without update the local folder. I will see how fix this

2024-06-28 22:13 UTC, CatHood0 commented
Yeah, i'm trying to resolve the before commit t

2024-06-28 22:28 UTC, singerdmx commented
@ellet0 I am going ahead and merging this. Please feel free to patch it after this.

2024-06-28 22:28 UTC, merged

2024-06-28 23:56 UTC, ellet0 commented on lib/src/utils/html2md_utils.dart
> +// ignore_for_file: implementation_imports
> @ellet0 Let's not block feature/fix. We can always refactor/reorganize code around later.

It would require making breaking changes.

2024-06-29 06:30 UTC, singerdmx commented on lib/src/utils/html2md_utils.dart
> +// ignore_for_file: implementation_imports
@ellet0 By breaking do you mean not backward compatible?

2024-06-29 06:32 UTC, singerdmx commented on lib/src/utils/html2md_utils.dart
> +// ignore_for_file: implementation_imports
If yes, I think it is acceptable and we just need to release with a major version change