enhance stringToColor with a custom defined palette from `DefaultStyles`
singerdmx/flutter-quill pull request #2095
Opened 2024-08-08 19:36 UTC by vishna

## Description

This change allows overriding and extending colors provided by `stringToColor`.  You're now able to define custom colors in `DefautStyles` e.g.:

```dart
palette: {
  "primary": Colors.red,
  "secondary": Colors.blue
}
```

and later use it:

```
BackgroundAttribute("primary")
```

### Why?

This is particularly useful if your app has multiple themes and some limited color set per each theme. Currently there is a big [switch](https://github.com/singerdmx/flutter-quill/blob/master/lib/src/common/utils/color.dart#L4) with hardcoded values in `stringToColor` which cannot be customized. This PR solves this problem without introducing any breaking changes.

## Related Issues

There was no issue for this.

## Type of Change

- [x] ✨ **New feature:** Adds new functionality without breaking existing features.
- [ ] 🛠️ **Bug fix:** Resolves an issue without altering current behavior.
- [ ] 🧹 **Code refactor:** Code restructuring that does not affect behavior.
- [ ] ❌ **Breaking change:** Alters existing functionality and requires updates.
- [ ] 🧪 **Tests:** Adds new tests or modifies existing tests.
- [ ] 📝 **Documentation:** Updates or additions to documentation.
- [ ] 🗑️ **Chore:** Routine tasks, or maintenance.
- [ ] ✅ **Build configuration change:** Changes to build or deploy processes.

## Suggestions

This switch could be a default palette https://github.com/singerdmx/flutter-quill/blob/master/lib/src/common/utils/color.dart#L4 🤔

2024-08-08 20:04 UTC, singerdmx requested changes

2024-08-08 20:04 UTC, singerdmx commented on lib/src/common/utils/color.dart
> +import '../../../flutter_quill.dart';
Do individual imports instead of importing everything

2024-08-08 20:06 UTC, singerdmx commented
@EchoEllet please have a look

2024-08-09 05:51 UTC, vishna commented on lib/src/common/utils/color.dart
> +import '../../../flutter_quill.dart';
done

2024-08-09 15:29 UTC, singerdmx commented
[   +2 ms] Target dart2js failed: ProcessException: Process exited abnormally with exit code 1:
           ../../../../.pub-cache/hosted/pub.dev/image_cropper_platform_interface-5.0.0/lib/src/models/cropped_file/html.dart:32:38:
           Error: The method 'UnmodifiableUint8ListView' isn't defined for the class 'CroppedFile'.
            - 'CroppedFile' is from 'package:image_cropper_platform_interface/src/models/cropped_file/html.dart' ('../../../../.pub-cache/hosted/pub.dev/image_cropper_platform_interface-5.0.0/lib/src/models/cropped_file/html.dart').
                 return Future<Uint8List>.value(UnmodifiableUint8ListView(_initBytes!));
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^
           Error: Compilation failed.
       
Not sure this error is related to your change.
@CatHood0 do you have a chance to have a look?

2024-08-09 16:21 UTC, CatHood0 commented
> @CatHood0 do you have a chance to have a look?

I will. Does the failed build occur on any platform or is it only for a certain platform?

2024-08-09 16:32 UTC, CatHood0 commented
I will assume of the issue happens when Compile the project. So, i think the version of the [image_cropper](https://pub.dev/packages/image_cropper) could be the problem (the lastest version of the package is `8.0.1`):

https://github.com/singerdmx/flutter-quill/blob/f93ce63dcb1322066004df88d1842af5a9f05c61/example/pubspec.yaml#L37-L38

2024-08-09 16:57 UTC, CatHood0 commented
@singerdmx `UnmodifiableUint8ListView` was depredcated on Dart 3.4 [see this](https://github.com/dart-lang/sdk/issues/53218)

2024-08-09 19:22 UTC, singerdmx commented
Ah I see

2024-08-11 17:31 UTC, singerdmx commented
> I think the version of the [image_cropper](https://pub.dev/packages/image_cropper) could be the main problem (the last version of the package is `8.0.1`):
> 
> https://github.com/singerdmx/flutter-quill/blob/f93ce63dcb1322066004df88d1842af5a9f05c61/example/pubspec.yaml#L37-L38
> 
> I will make a PR solving this soon

@CatHood0 how did it go?

2024-08-11 22:08 UTC, singerdmx commented
@vishna could you please rebase?

2024-08-20 04:07 UTC, merged